[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
optimizer = true
viaIR= true
optimizer_runs = 200
gas_reports = ["*"]
auto_detect_solc = false

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 128
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true

[profile.ci]
fuzz_runs = 10000
invariant_runs = 1000